

package com.manicken;

//Generated by GuiGenie - Copyright (c) 2004 Mario Awad.
//Home Page http://guigenie.cjb.net - Check often for new versions!

import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import javax.swing.event.*;

public class ConfigDialog extends JPanel {

    public JLabel lblServerport;
    public JLabel lblTermCapWebSocketServerPort;
    public JTextField txtWebServerPort;
    public JLabel lblBiDirDataWebSocketServerPort;
    public JTextField txtBiDirDataWebSocketServerPort;
    public JCheckBox chkAutostart;
    public JCheckBox chkDebugMode;
    public JList lstMidiDeviceIn;
    public JList lstMidiDeviceOut;
    public JButton btnRefreshMidiDevices;
    public JTextField txtTermCapWebSocketServerPort;

    public ConfigDialog() {
        //construct preComponents
        String[] jcomp8Items = {};

        //construct components
        lblServerport = new JLabel ("WebServer Port");
        lblTermCapWebSocketServerPort = new JLabel ("Terminal Capture WebSocket Server Port");
        txtWebServerPort = new JTextField (5);
        lblBiDirDataWebSocketServerPort = new JLabel ("BiDir Data WebSocket Server Port");
        txtBiDirDataWebSocketServerPort = new JTextField (5);
        chkAutostart = new JCheckBox ("Autostart Server at Arduino IDE start");
        chkDebugMode = new JCheckBox ("Activates some debug output");
        lstMidiDeviceIn = new JList (jcomp8Items);
        lstMidiDeviceOut = new JList (jcomp8Items);
        btnRefreshMidiDevices = new JButton ("Refresh MIDI Devices");
        txtTermCapWebSocketServerPort = new JTextField (5);

        //adjust size and set layout
        setPreferredSize (new Dimension (450, 574));
        setLayout (null);

        //add components
        add (lblServerport);
        add (lblTermCapWebSocketServerPort);
        add (txtWebServerPort);
        add (lblBiDirDataWebSocketServerPort);
        add (txtBiDirDataWebSocketServerPort);
        add (chkAutostart);
        add (chkDebugMode);
        add (lstMidiDeviceIn);
        add (lstMidiDeviceOut);
        add (btnRefreshMidiDevices);
        add (txtTermCapWebSocketServerPort);

        //set component bounds (only needed by Absolute Positioning)
        lblServerport.setBounds (60, 5, 100, 25);
        lblTermCapWebSocketServerPort.setBounds (60, 35, 240, 25);
        txtWebServerPort.setBounds (5, 5, 50, 25);
        lblBiDirDataWebSocketServerPort.setBounds (60, 65, 205, 25);
        txtBiDirDataWebSocketServerPort.setBounds (5, 65, 50, 25);
        chkAutostart.setBounds (5, 100, 245, 25);
        chkDebugMode.setBounds (5, 130, 195, 20);
        lstMidiDeviceIn.setBounds (5, 205, 200, 355);
        lstMidiDeviceOut.setBounds (210, 205, 200, 355);
        btnRefreshMidiDevices.setBounds (5, 175, 285, 25);
        txtTermCapWebSocketServerPort.setBounds (5, 35, 50, 25);
    }

}
