

package com.manicken;

//Generated by GuiGenie - Copyright (c) 2004 Mario Awad.
//Home Page http://guigenie.cjb.net - Check often for new versions!

import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import javax.swing.event.*;

public class MidiDeviceSelectDialog extends JPanel {

    
    public JLabel lblMidiDeviceIn;
    public JLabel lblMidiDeviceOut;
    public JList lstMidiDeviceIn;
    public JList lstMidiDeviceOut;
    public JButton btnRefreshMidiDevices;

    public MidiDeviceSelectDialog() {
        //construct preComponents
        String[] jcomp8Items = {};

        //construct components
        lblMidiDeviceIn = new JLabel ("Input Devices");
        lblMidiDeviceOut = new JLabel ("Output Devices");
        lstMidiDeviceIn = new JList (jcomp8Items);
        lstMidiDeviceOut = new JList (jcomp8Items);
        btnRefreshMidiDevices = new JButton ("Refresh MIDI Devices");
        //adjust size and set layout
        setPreferredSize (new Dimension (515, 404));
        setLayout (null);

        //add components
        add (lblMidiDeviceIn);
        add (lblMidiDeviceOut);
        add (lstMidiDeviceIn);
        add (lstMidiDeviceOut);
        add (btnRefreshMidiDevices);

        //set component bounds (only needed by Absolute Positioning)
        btnRefreshMidiDevices.setBounds (5, 5, 300, 25);
        lblMidiDeviceIn.setBounds(5, 35, 250, 25);
        lstMidiDeviceIn.setBounds (5, 60, 250, 355);
        lblMidiDeviceOut.setBounds(260, 35, 250, 25);
        lstMidiDeviceOut.setBounds (260, 60, 250, 355);
        
    }

}
